### ISSUE TITLE
Image preview

### ISSUE THREAD

**Issue by omerziger** [omerziger/use-file-wizard#11]
Add an option to return preview of an image as url for example

**Comment by omerziger** [comment]
Prop (preview: boolean) adde to useFileWizard hook, the hook now also returns (filePreview: (url: string))
that can be placed in the src attribute of "img" element

**Comment by bliyscom** [comment]
I don't know why getfilepreview does not return url. It used to be the case but for some reason, it no longer works. I'm really starting to get discouraged. Plus, storage caches image Id, inconveniencing

**Comment by omerziger** [comment]
Hey @bliyscom ,you may confused my repo for another.
But if you're already here, this package will soon be published I hope you'll give it a look :)
